#pragma once

#include "RE/A/Actor.h"
#include "RE/C/CombatBehaviorContextMagic.h"
#include "RE/C/CombatBehaviorContextRangedMovement.h"
#include "RE/C/CombatBehaviorExpression.h"
#include "RE/C/CombatBehaviorTreeUtils.h"
#include "RE/C/CombatBehaviorTreeValueNode.h"
#include "RE/C/CombatController.h"
#include "RE/C/CombatGroup.h"
#include "RE/C/CombatInventory.h"
#include "RE/C/CombatState.h"
#include "RE/T/TESCombatStyle.h"

namespace RE
{
	template <typename T, typename Expr>
	class CombatBehaviorTreeValueNodeTImpl : public CombatBehaviorTreeValueNode<T>
	{
	public:
		CombatBehaviorTreeValueNodeTImpl(auto&& expr) :
			expr(std::forward<decltype(expr)>(expr)) {}

		T GetValue() override
		{
			return static_cast<T>(expr);
		}

		// members
		Expr expr;  // 30
	};

	template <typename T, typename Expr>
	class CombatBehaviorTreeValueNodeT : public CombatBehaviorTreeValueNodeTImpl<T, Expr>
	{
	public:
		using CombatBehaviorTreeValueNodeTImpl<T, Expr>::CombatBehaviorTreeValueNodeTImpl;
	};

	// Specs for instantiated nodes

#define DECLARE_SPECIALIZATION(T, Expr, size, SE_ARR, AE_ARR)                                      \
	template <>                                                                                    \
	class CombatBehaviorTreeValueNodeT<T, Expr> : public CombatBehaviorTreeValueNodeTImpl<T, Expr> \
	{                                                                                              \
	public:                                                                                        \
		CombatBehaviorTreeValueNodeT(auto&& expr) :                                                \
			CombatBehaviorTreeValueNodeTImpl<T, Expr>(std::forward<decltype(expr)>(expr))          \
		{                                                                                          \
			this->SetVftable(RELOCATION_ID((SE_ARR)[0].id(), (AE_ARR)[0].id()));                   \
		}                                                                                          \
	};                                                                                             \
	
	// sizeof instatiates template, so use for tests
	//static_assert(sizeof(CombatBehaviorTreeValueNodeT<T, Expr>) == (size))

#define COMMA ,
	DECLARE_SPECIALIZATION(unsigned int, int, 0x38, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_int_, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, MagicSystem::CastingType, 0x38, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_MagicSystem__CastingType_, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatInventoryItem::TYPE, 0x38, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatInventoryItem__TYPE_, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorUnaryExpression<CombatBehaviorMemberFunc<CombatState COMMA decltype(&CombatState::QTargetLost)> COMMA OpNot>>, 0x38, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorUnaryExpression_CombatBehaviorMemberFunc_CombatState_bool_CombatState____void___OpNot___, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorUnaryExpression<CombatBehaviorMemberFunc<CombatBehaviorEquipContext COMMA decltype(&CombatBehaviorEquipContext::CheckEquipmentChanged)> COMMA OpNot>>, 0x38, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorUnaryExpression_CombatBehaviorMemberFunc_CombatBehaviorEquipContext_bool_CombatBehaviorEquipContext____void___OpNot___, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorUnaryExpression<CombatBehaviorMemberFunc<CombatController COMMA decltype(&CombatController::CheckCombatArea) COMMA CombatBehaviorTreeUtils::CombatBehaviorAttacker> COMMA OpNot>>, 0x40, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorUnaryExpression_CombatBehaviorMemberFunc1_CombatController_bool_CombatController____Actor__CombatBehaviorTree__CombatBehaviorAttacker__OpNot___, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                            // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorMemberFunc<CombatState COMMA decltype(&CombatState::CheckShouldHide)>>, 0x38, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorMemberFunc_CombatState_bool_CombatState____void____, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorMemberFunc<CombatGroup COMMA decltype(&CombatGroup::IsSearching)>>, 0x38, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorMemberFunc_CombatGroup_bool_CombatGroup____void____, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorMemberFunc<CombatBehaviorEquipContext COMMA decltype(&CombatBehaviorEquipContext::GetEquipmentType)>>, 0x38, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorMemberFunc_CombatBehaviorEquipContext_CombatInventoryItem__TYPE_CombatBehaviorEquipContext____void____, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorMemberFunc<CombatBehaviorContextRangedMovement COMMA decltype(&CombatBehaviorContextRangedMovement::CheckOutOfRange)>>, 0x38, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorMemberFunc_CombatBehaviorContextRangedMovement_bool_CombatBehaviorContextRangedMovement____void____, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorMemberFunc<CombatBehaviorContextMagic COMMA decltype(&CombatBehaviorContextMagic::GetCastingType)>>, 0x38, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorMemberFunc_CombatBehaviorContextMagic_MagicSystem__CastingType_CombatBehaviorContextMagic____void____, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorMemberFunc<CombatBehaviorContextCloseMovement COMMA decltype(&CombatBehaviorContextCloseMovement::CheckOutOfRange)>>, 0x38, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorMemberFunc_CombatBehaviorContextCloseMovement_bool_CombatBehaviorContextCloseMovement____void____, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorMemberFunc<Actor COMMA decltype(&Actor::CanStrafe)>>, 0x38, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorMemberFunc_Actor_bool_IMovementState____void____, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorMemberFunc<Actor COMMA decltype(&ActorState::IsFlying)>>, 0x38, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorMemberFunc_Actor_bool_ActorState____void____, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorMemberFunc<TESCombatStyle COMMA decltype(&TESCombatStyle::HasFlag) COMMA TESCombatStyle::FLAG>>, 0x40, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorMemberFunc1_TESCombatStyle_bool_TESCombatStyle____unsignedint__TESCombatStyle__FLAG___, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorBinaryExpression<CombatBehaviorUnaryExpression<CombatBehaviorMemberFunc<CombatState COMMA decltype(&CombatState::QTargetLost)> COMMA OpNot> COMMA CombatBehaviorExpression<CombatBehaviorBinaryExpression<CombatBehaviorFunc<float (*)(TESObjectREFR* COMMA TESObjectREFR*) COMMA CombatBehaviorTreeUtils::CombatBehaviorAttacker COMMA CombatBehaviorTreeUtils::CombatBehaviorTarget> COMMA float COMMA OpLessThan>> COMMA OpAnd>>, 0x50, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorBinaryExpression_CombatBehaviorUnaryExpression_CombatBehaviorMemberFunc_CombatState_bool_CombatState____void___OpNot__CombatBehaviorExpression_CombatBehaviorBinaryExpression_CombatBehaviorFunc2_float___TESObjectREFR_TESObjectREFR__CombatBehaviorTree__CombatBehaviorAttacker_CombatBehaviorTree__CombatBehaviorTarget__float_OpLessThan___OpAnd___, 0);  // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorBinaryExpression<CombatBehaviorMemberFunc<CombatInventory COMMA decltype(&CombatInventory::QRawMaxRange)> COMMA float COMMA OpGreaterThan>>, 0x40, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorBinaryExpression_CombatBehaviorMemberFunc_CombatInventory_float_CombatInventory____void___float_OpGreaterThan___, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorBinaryExpression<CombatBehaviorMemberFunc<Actor COMMA decltype(&ActorState::GetFlyState)> COMMA FLY_STATE COMMA OpEquals>>, 0x40, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorBinaryExpression_CombatBehaviorMemberFunc_Actor_FLY_STATE_ActorState____void___FLY_STATE_OpEquals___, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorBinaryExpression<CombatBehaviorMemberFunc<Actor COMMA decltype(&Actor::IsOnWaterTriangle)> COMMA CombatBehaviorExpression<CombatBehaviorUnaryExpression<CombatBehaviorMemberFunc<Actor COMMA decltype(&Actor::FightsInWater)> COMMA OpNot>> COMMA OpAnd>>, 0x50, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorBinaryExpression_CombatBehaviorMemberFunc_Actor_bool_Actor____void___CombatBehaviorExpression_CombatBehaviorUnaryExpression_CombatBehaviorMemberFunc_Actor_bool_Actor____void___OpNot___OpAnd___, 0);                                                                                                                                                                                                                                                                                                                                   // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorBinaryExpression<CombatBehaviorMemberFunc<Actor COMMA decltype(&Actor::CanFly)> COMMA CombatBehaviorExpression<CombatBehaviorBinaryExpression<CombatBehaviorMemberFunc<Actor COMMA decltype(&ActorState::GetFlyState)> COMMA FLY_STATE COMMA OpNotEquals>> COMMA OpOr>>, 0x50, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorBinaryExpression_CombatBehaviorMemberFunc_Actor_bool_Actor____void___CombatBehaviorExpression_CombatBehaviorBinaryExpression_CombatBehaviorMemberFunc_Actor_FLY_STATE_ActorState____void___FLY_STATE_OpNotEquals___OpOr___, 0);                                                                                                                                                                                                                                                                                           // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorBinaryExpression<CombatBehaviorMemberFunc<CombatState COMMA decltype(&CombatState::CheckShouldFlee)> COMMA CombatBehaviorExpression<CombatBehaviorMemberFunc<Actor COMMA decltype(&Actor::IsInBleedout)>> COMMA OpOr>>, 0x48, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorBinaryExpression_CombatBehaviorMemberFunc_CombatState_bool_CombatState____void___CombatBehaviorExpression_CombatBehaviorMemberFunc_Actor_bool_Actor____void____OpOr___, 0);                                                                                                                                                                                                                                                                                                                                                                                                // I do not know for AE
	DECLARE_SPECIALIZATION(unsigned int, CombatBehaviorExpression<CombatBehaviorMemberFunc<Actor COMMA decltype(&Actor::IsEssentialDown)>>, 0x40, RE::VTABLE_CombatBehaviorTreeValueNodeT_unsignedint_CombatBehaviorExpression_CombatBehaviorMemberFunc_Actor_bool_Actor____void____, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // I do not know for AE
	DECLARE_SPECIALIZATION(float, CombatBehaviorExpression<CombatBehaviorFunc<float (*)(Actor*) COMMA CombatBehaviorTreeUtils::CombatBehaviorAttacker>>, 0x40, RE::VTABLE_CombatBehaviorTreeValueNodeT_float_CombatBehaviorExpression_CombatBehaviorFunc1_float___Actor__CombatBehaviorTree__CombatBehaviorAttacker___, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // I do not know for AE
#undef COMMA

#undef DECLARE_SPECIALIZATION
}
